using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public class MfaCodeTable
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]               // Specifies that the value of a property will be generated by the Identity database. https://www.entityframeworktutorial.net/code-first/databasegenerated-dataannotations-attribute.aspx
        public string Id { get; set; }
        public string UserId { get; set; }
        public string MFA_Code { get; set; }
        public DateTime DateCodeIssued { get; set; }
        public DateTime DateCodeExpires { get; set; }


        [ForeignKey("UserId")]
        public AppUser User { get; set; }
    }
}
