using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public class RefreshTokenTable

    // https://stackoverflow.com/questions/62485906/how-to-add-tables-and-relations-to-generated-asp-net-core-mvc-identity-database

    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]               // Specifies that the value of a property will be generated by the Identity database. https://www.entityframeworktutorial.net/code-first/databasegenerated-dataannotations-attribute.aspx
        public string Id { get; set; }
        public string UserId { get; set; }
        public string RefreshToken { get; set; }
        public DateTime DateTokenIssued { get; set; }
        public DateTime DateTokenExpires { get; set; }


        [ForeignKey("UserId")]
        public AppUser User { get; set; }
    }
}
